language: node_js
node_js:
  - "0.10"

install:
  - npm install -g grunt-cli
  - npm install

env:
    - COVERALLS_REPO_TOKEN=TCpLixkryTQl8qimcZhItmwpeUnesQYhu

after_success:
    cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js